version: '3.8'
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: excalt
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d excalt'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: java -jar addpp-0.0.1-SNAPSHOT.jar
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/excalt
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password



