spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/excalt
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql

server:
  port: 8081

app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKey
  jwtExpiration: 86400000

